server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 网关名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes:
        - id: cloud-user # 路由标示，必须唯一
          uri: lb://userserver # 路由的目标地址
#          uri: http://localhost:8101
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: cloud-order
#          uri: lb://orderserver
          uri: http://localhost:8100
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!