# -------------------- spring配置
spring:
  # -------------------- jdbc配置
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  # -------------------- 静态资源配置
#  mvc:
#    static-path-pattern: /**
#  web:
#    resources:
#      static-locations: classpath:/public/, classpath:/static/, file:${upload.location}/
#      chain:
#        strategy:
#          content:
#            enabled: true # 内容版本管理策略会给静态文件添加随机hash值
#            paths: /**


# -------------------- Mybatis-plus的配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.order.entity
  configuration:
    map-underscore-to-camel-case: true
