# 服务端口配置
server:
  port: 8300

spring:
  # jdbc配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 12345678
# 配置服务的名字
  application:
    name: cloud-sentinel

# 服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 服务发现的地址，就是nacos的地址

# sentinel配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090 # 配置Sentinel控制面板的URL
        port: 9999 # 任意设置一个没有占用的端口即可
      log:
        dir: logs/sentinel # 日志目录
      enabled: true # 开启Sentinel

# 开启Sentinel和OpenFeign配置
feign:
  sentinel:
    enabled: true
