spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.0.128:8090
        port: 8719

  # -------------------- jdbc配置
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678